services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-pix-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/cron/crontab:/etc/cron.d/laravel-cron
      - ./docker/cron/logs:/var/log/cron
    depends_on:
      - mysql
    networks:
      - laravel-pix-network

  mysql:
    image: mysql:8.0
    container_name: laravel-pix-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_pix
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-pix-network

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-pix-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-pix-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-pix-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - laravel-pix-network

networks:
  laravel-pix-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
